### ISSUE TITLE
Connection error with modbus after upgrade

### ISSUE THREAD

**Issue by chakalaka91** [OpenEMS/openems#3081]
### Description

Hey all,

I'm using the modbus integration to pull data from my Fenecon inverter, which has a modbus/TCP API.

Since setting up some years ago this worked just fine, however since yesterday it doesn't work anymore. 

The entities are not available anymore, since I've upgraded to FEMS Version 2025.3.2.

![Image](https://github.com/user-attachments/assets/bb917a3f-c3b2-41a1-989b-6e4f9595a4ef)

I'd be glad if anyone could help me this, since I could'nt get behind, why this doesn't work anymore. To me the configuration seems correct. Since I didn't change anything by myself, the only thing which changed was the upgrade to the version 2025.3.2.

Kind regards

### Operating System

Home Assistant OS 15.1 | Home Assistant Core 2025.3.4

### Example YAML snippet

```yaml
- name: "fems"
  delay: 0
  timeout: 5
  type: tcp
  host: 192.168.178.199
  port: 502
  
  sensors:
    #INT
    - name: "FEMS_EssSoc" # Battery SoC
      scan_interval: 60 
      data_type: uint16
      input_type: input
      device_class: battery
      state_class: measurement
      unit_of_measurement: "%"
      address: 302
      slave: 1
      unique_id: fems_modbus_302

    #FLOAT32      
    - name: "FEMS_EssActivePower" # Combined Power of PV + Battery
      unit_of_measurement: W
      scan_interval: 10
      data_type: float32
      input_type: holding
      device_class: power
      state_class: measurement
      address: 303
      slave: 1
      unique_id: fems_modbus_303

    - name: "FEMS_GridActivePower" # Grid Power
      unit_of_measurement: W
      scan_interval: 10 
      data_type: float32
      input_type: holding
      device_class: power
      state_class: measurement
      address: 315
      slave: 1
      unique_id: fems_modbus_315

    - name: "FEMS_ProductionActualPower" # PV Power
      unit_of_measurement: W
      scan_interval: 10
      data_type: float32
      input_type: holding
      device_class: power
      state_class: measurement
      address: 339
      slave: 1
      unique_id: fems_modbus_339
      
    - name: "FEMS_ConsumptionActivePower" #House Power
      unit_of_measurement: W
      scan_interval: 10
      data_type: float32
      input_type: holding
      device_class: power
      state_class: measurement
      address: 343
      slave: 1
      unique_id: fems_modbus_343
      
            
    - name: "FEMS_EssDischargePower"  #Battery Discharge Power
      unit_of_measurement: W
      scan_interval: 5 
      data_type: float32
      input_type: holding
      device_class: power
      state_class: measurement
      address: 415
      slave: 1
      unique_id: fems_modbus_415
      
    #Energy  (Float64)
      
    - name: "FEMS_GridBuyActiveEnergy" #Total Consumption from Grid
      unit_of_measurement: Wh
      scan_interval: 60 
      data_type: float64
      input_type: holding
      device_class: energy
      state_class: total_increasing
      address: 359
      slave: 1
      unique_id: fems_modbus_359 
      
    - name: "FEMS_GridSellActiveEnergy" #Total Energy Sold to Grid
      unit_of_measurement: Wh
      scan_interval: 60 
      data_type: float64
      input_type: holding
      device_class: energy
      state_class: total_increasing
      address: 363
      slave: 1
      unique_id: fems_modbus_363

    - name: "FEMS_ProductionActiveEnergy" # Total PV Production Energy
      unit_of_measurement: Wh
      scan_interval: 60 
      data_type: float64
      input_type: holding
      device_class: energy
      state_class: total_increasing
      address: 367
      slave: 1
      unique_id: fems_modbus_367
      
    - name: "FEMS_ConsumptionActiveEnergy" # Total Energy Usage
      unit_of_measurement: Wh
      scan_interval: 60 
      data_type: float64
      input_type: holding
      device_class: energy
      state_class: total_increasing
      address: 379
      slave: 1
      unique_id: fems_modbus_379
      
    - name: "FEMS_EssDcChargeEnergy" # Total Battery Charge Energy
      unit_of_measurement: Wh
      scan_interval: 60 
      data_type: float64
      input_type: holding
      device_class: energy
      state_class: total_increasing
      address: 383
      slave: 1
      unique_id: fems_modbus_383
      
    - name: "FEMS_EssDcDischargeEnergy" # Total Battery Discharge Energy
      unit_of_measurement: Wh
      scan_interval: 60 
      data_type: float64
      input_type: holding
      device_class: energy
      state_class: total_increasing
      address: 387
      slave: 1
      unique_id: fems_modbus_387
```

### How to reproduce the Error?

An excerpt of the debug protocol gave me this: 
_2025-03-31 13:54:20.757 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 111] Connect call failed ('192.168.178.199', 502)
2025-03-31 13:54:22.050 ERROR (MainThread) [homeassistant.components.modbus.modbus] Pymodbus: fems: Error: device: 1 address: 415 -> Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.178.199:502]
2025-03-31 13:54:25.961 WARNING (MainThread) [pymodbus.logging] Failed to connect 
2025-03-31 13:54:31.365 WARNING (MainThread) [pymodbus.logging] Failed to connect 
2025-03-31 13:54:37.167 WARNING (MainThread) [pymodbus.logging] Failed to connect 
2025-03-31 13:54:38.776 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 111] Connect call failed ('192.168.178.199', 502)
2025-03-31 13:54:41.982 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 111] Connect call failed ('192.168.178.199', 502)
2025-03-31 13:54:48.389 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 111] Connect call failed ('192.168.178.199', 502)
2025-03-31 13:55:01.195 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 111] Connect call failed ('192.168.178.199', 502)
2025-03-31 13:58:42.095 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x89 0x0 0x0 0x0 0x6 0x1 0x3 0x1 0x9f 0x0 0x2
2025-03-31 13:58:42.101 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x89 0x0 0x0 0x0 0x7 0x1 0x3 0x4 0xff 0xff 0xff 0xff old_data:  addr=None
2025-03-31 13:58:42.102 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x89 0x0 0x0 0x0 0x7 0x1 0x3 0x4 0xff 0xff 0xff 0xff
2025-03-31 13:58:42.102 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[65535, 65535], status=1) 
2025-03-31 13:58:42.102 DEBUG (MainThread) [pymodbus.logging] Frame advanced, resetting header!!
2025-03-31 13:58:43.127 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x8a 0x0 0x0 0x0 0x6 0x1 0x3 0x1 0x2f 0x0 0x2
2025-03-31 13:58:43.130 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x8a 0x0 0x0 0x0 0x7 0x1 0x3 0x4 0xff 0xff 0xff 0xff old_data:  addr=None
2025-03-31 13:58:43.130 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x8a 0x0 0x0 0x0 0x7 0x1 0x3 0x4 0xff 0xff 0xff 0xff
2025-03-31 13:58:43.131 DEBUG (MainThread) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[65535, 65535], status=1)_ 

It then tries to reset the header several more times.
